export default [
  { type: "section_divider", titie: "", title: "Section title goes here" },
  {
    type: "TextField",
    title: "Text label",
    description: "",
    value: "",
    reference_target_type_id: null,
    reference_target_id: null,
    settings: {
      required: true,
      isLimited: true,
      max: 50,
      defaultNum: 5,
      pastOnly: false,
      futureOnly: false,
      quickMenu: false,
      includeTime: false,
      dateRange: false,
      dateType: "date",
      datePlaceHolder: "Pick a day",
      dateFormat: "yyyy/MM/dd",
      single: true,
      matrix_questions: "",
      matrix_choices: "",
      options: ""
    }
  },
  {
    type: "NumberField",
    title: "Numeric label",
    description: "",
    value: "",
    reference_target_type_id: null,
    reference_target_id: null,
    settings: {
      required: true,
      isLimited: true,
      max: "5",
      defaultNum: 5,
      pastOnly: false,
      futureOnly: false,
      quickMenu: false,
      includeTime: false,
      dateRange: false,
      dateType: "date",
      datePlaceHolder: "Pick a day",
      dateFormat: "yyyy/MM/dd",
      single: true,
      matrix_questions: "",
      matrix_choices: "",
      options: ""
    }
  },
  {
    type: "TextBox",
    title: "Paragraph label",
    description: "",
    value: "",
    reference_target_type_id: null,
    reference_target_id: null,
    settings: {
      required: true,
      isLimited: true,
      max: 50,
      defaultNum: 5,
      pastOnly: false,
      futureOnly: false,
      quickMenu: false,
      includeTime: false,
      dateRange: false,
      dateType: "date",
      datePlaceHolder: "Pick a day",
      dateFormat: "yyyy/MM/dd",
      single: true,
      matrix_questions: "",
      matrix_choices: "",
      options: ""
    }
  },
  {
    type: "DateTimeField",
    title: "Date label",
    description: "",
    value: "",
    reference_target_type_id: null,
    reference_target_id: null,
    settings: {
      required: false,
      isLimited: false,
      max: 50,
      defaultNum: 5,
      pastOnly: false,
      futureOnly: false,
      quickMenu: false,
      includeTime: false,
      dateRange: false,
      dateType: "date",
      datePlaceHolder: "Pick a day",
      dateFormat: "yyyy/MM/dd",
      single: true,
      matrix_questions: "",
      matrix_choices: "",
      options: ""
    }
  },
  {
    type: "TimeField",
    title: "Time label",
    description: "",
    value: "",
    reference_target_type_id: null,
    reference_target_id: null,
    settings: {
      required: false,
      isLimited: false,
      max: 50,
      defaultNum: 5,
      pastOnly: false,
      futureOnly: false,
      quickMenu: false,
      includeTime: false,
      dateRange: false,
      dateType: "date",
      datePlaceHolder: "Pick a day",
      dateFormat: "yyyy/MM/dd",
      single: true,
      matrix_questions: "",
      matrix_choices: "",
      options: ""
    }
  }
];
